### ISSUE TITLE
Can I work on a Responsive Navigation Bar and Password Generator.  

### ISSUE THREAD

**Issue by ak4631** [TheGuyDangerous/MernStack#11]

**Comment by TheGuyDangerous** [comment]
Hi @ak4631 , Create 2 separate issues , for both the templates.

- Do not write your query in the Title of your issue.
- Create a Proper Description stating what the template would look like, including pics/screenshots/reference to it.
- I'm closing this issue for now, as it is incomplete and does not follow the [contributing](https://github.com/TheGuyDangerous/MernStack/blob/main/CONTRIBUTING.md) guidelines.
